import React from 'react';
import QuestionBankTable from './QuestionBankTable';
import { Questions } from '../../../types';

const sampleQuestions = [
    {
      id: 1,
      category: 'Geography',
      difficulty: 'easy',
      question: 'What is the capital of France?',
      options: ['Paris', 'London', 'Berlin', 'Madrid'],
      answer: 'Paris',
      favourited: false,
      timestamp: new Date(),
    },
    {
      id: 2,
      category: 'Mathematics',
      difficulty: 'medium',
      question: 'What is 2 + 2?',
      options: ['3', '4', '5', '6'],
      answer: '4',
      favourited: false,
      timestamp: new Date(),
    },
    {
      id: 3,
      category: 'Science',
      difficulty: 'easy',
      question: 'What planet is known as the Red Planet?',
      options: ['Earth', 'Mars', 'Jupiter', 'Saturn'],
      answer: 'Mars',
      favourited: false,
      timestamp: new Date(),
    },
    {
      id: 4,
      category: 'History',
      difficulty: 'hard',
      question: 'Who was the first president of the United States?',
      options: ['Thomas Jefferson', 'Abraham Lincoln', 'George Washington', 'John Adams'],
      answer: 'George Washington',
      favourited: false,
      timestamp: new Date(),
    },
    {
      id: 5,
      category: 'Pop Culture',
      difficulty: 'medium',
      question: 'Who wrote the song "Imagine"?',
      options: ['John Lennon', 'Paul McCartney', 'George Harrison', 'Ringo Starr'],
      answer: 'John Lennon',
      favourited: false,
      timestamp: new Date(),
    },
    {
      id: 6,
      category: 'Literature',
      difficulty: 'easy',
      question: 'Who wrote "Romeo and Juliet"?',
      options: ['William Shakespeare', 'Charles Dickens', 'Jane Austen', 'Mark Twain'],
      answer: 'William Shakespeare',
      favourited: false,
      timestamp: new Date(),
    },
    {
      id: 7,
      category: 'Music',
      difficulty: 'medium',
      question: 'Who is known as the King of Pop?',
      options: ['Elvis Presley', 'Michael Jackson', 'Prince', 'Madonna'],
      answer: 'Michael Jackson',
      favourited: false,
      timestamp: new Date(),
    },
    {
      id: 8,
      category: 'Geography',
      difficulty: 'hard',
      question: 'What is the longest river in the world?',
      options: ['Amazon', 'Nile', 'Yangtze', 'Mississippi'],
      answer: 'Nile',
      favourited: false,
      timestamp: new Date(),
    },
    {
      id: 9,
      category: 'Science',
      difficulty: 'medium',
      question: 'What is the chemical symbol for water?',
      options: ['O2', 'H2O', 'CO2', 'NaCl'],
      answer: 'H2O',
      favourited: false,
      timestamp: new Date(),
    },
    {
      id: 10,
      category: 'Mathematics',
      difficulty: 'hard',
      question: 'What is the square root of 144?',
      options: ['10', '11', '12', '13'],
      answer: '12',
      favourited: false,
      timestamp: new Date(),
    },
    {
      id: 11,
      category: 'History',
      difficulty: 'easy',
      question: 'In what year did the Titanic sink?',
      options: ['1912', '1905', '1920', '1915'],
      answer: '1912',
      favourited: false,
      timestamp: new Date(),
    },
    {
      id: 12,
      category: 'Pop Culture',
      difficulty: 'easy',
      question: 'Who played Jack in the movie "Titanic"?',
      options: ['Brad Pitt', 'Leonardo DiCaprio', 'Johnny Depp', 'Tom Cruise'],
      answer: 'Leonardo DiCaprio',
      favourited: false,
      timestamp: new Date(),
    },
    {
      id: 13,
      category: 'Literature',
      difficulty: 'hard',
      question: 'Who wrote "Moby-Dick"?',
      options: ['Herman Melville', 'F. Scott Fitzgerald', 'Ernest Hemingway', 'J.D. Salinger'],
      answer: 'Herman Melville',
      favourited: false,
      timestamp: new Date(),
    },
    {
      id: 14,
      category: 'Music',
      difficulty: 'hard',
      question: 'Which composer is known for his "Fifth Symphony"?',
      options: ['Mozart', 'Beethoven', 'Bach', 'Chopin'],
      answer: 'Beethoven',
      favourited: false,
      timestamp: new Date(),
    },
    {
      id: 15,
      category: 'Geography',
      difficulty: 'medium',
      question: 'What is the capital of Australia?',
      options: ['Sydney', 'Melbourne', 'Canberra', 'Brisbane'],
      answer: 'Canberra',
      favourited: false,
      timestamp: new Date(),
    },
  ];
  

function Test() {
  return (
    <div className='App'>
      <QuestionBankTable questions={sampleQuestions} />
    </div>
  );
}

export default Test;
